version: '3'
services:
 # mongo config server
  mongo-config-1:
    container_name: mongo-config-1
    hostname: mongo-config-1
    image: mongo
    command: mongod --configsvr --replSet mongo-config-rs-1 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/config1:/data/db

  mongo-config-2:
    container_name: mongo-config-2
    hostname: mongo-config-2
    image: mongo
    command: mongod --configsvr --replSet mongo-config-rs-1 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/config2:/data/db

  mongo-config-3:
    container_name: mongo-config-3
    hostname: mongo-config-3
    image: mongo
    command: mongod --configsvr --replSet mongo-config-rs-1 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/config3:/data/db

# shard replica set 1
  mongo-shard1-rs1:
    container_name: mongo-shard1-rs1
    hostname: mongo-shard1-rs1
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/data1:/data/db

  mongo-shard1-rs2:
    container_name: mongo-shard1-rs2
    hostname: mongo-shard1-rs2
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/data2:/data/db

  mongo-shard1-rs3:
    container_name: mongo-shard1-rs3
    hostname: mongo-shard1-rs3
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/data3:/data/db

# shard replica set 2
  mongo-shard2-rs1:
    container_name: mongo-shard2-rs1
    hostname: mongo-shard2-rs1
    image: mongo
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/data4:/data/db

  mongo-shard2-rs2:
    container_name: mongo-shard2-rs2
    hostname: mongo-shard2-rs2
    image: mongo
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/data5:/data/db

  mongo-shard2-rs3:
    container_name: mongo-shard2-rs3
    hostname: mongo-shard2-rs3
    image: mongo
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongo_sharding/data6:/data/db

# mongos
  mongos1:
    container_name: mongos1
    hostname: mongos1
    image: mongo
    depends_on:
      - mongo-config-1
      - mongo-config-2
      - mongo-config-3
    command: mongos --configdb mongors1conf/mongo-config-1,mongo-config-2,mongo-config-3 --bind_ip_all
    ports:
      - 27017:27017

  mongos2:
    container_name: mongos2
    hostname: mongos2
    image: mongo
    depends_on:
      - mongo-config-1
      - mongo-config-2
      - mongo-config-3
    command: mongos --configdb mongors1conf/mongo-config-1,mongo-config-2,mongo-config-3 --bind_ip_all
    ports:
      - 27016:27017
